<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>RightMenu.Runner</RootNamespace>
    <AssemblyName>RightMenu.Runner</AssemblyName>
    <ApplicationIcon>..\RightMenu.App\Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RightMenu.Core\RightMenu.Core.csproj" />
  </ItemGroup>

</Project>
